# What is PyTorch?
Two main use cases:
1. Leverage numpy arrays on the GPU
2. Deep learning research platform

In [1]:
# Import Libraries
import torch
import numpy as np
import torch.nn as nn

# Part 1: Intro to Tensors
- Tensors are a fundamental data structure similiar to arrays and matrices
- Efficient for math operations on large data 
- The data structure used in pytorch models
- Similiar to a numpy array

In [2]:
# Creating a Tensor from a Numpy Array
ndarray = np.array([1, 2, 3])
t = torch.from_numpy(ndarray)
print("Tensor: ", t)

Tensor:  tensor([1, 2, 3])


### Three Attributes of a Tensor:
1. shape: size of the tensor
2. data type: type of data stored in the tensor
3. device: the device the tensor is stored in (e.g. cpu, gpu)

In [3]:
print(t.shape)
print(t.dtype)
print(t.device)

torch.Size([3])
torch.int64
cpu


### Tensor Operations

In [4]:
ndarray = np.array([[0, 1, 2], [3, 4, 5]])
tensor_2 = torch.from_numpy(ndarray)

# Index first row:
print("First row: ", tensor_2[0])

# Index first column:
print("First column: ", tensor_2[:, 0])

# Transpose the tensor
print("Transpose: \n", tensor_2.T)

# Multiply the Tensor: (Matrix Multiplication)
ndarray = np.array([[2, 2, 2], [3, 3, 3], [6, 7, 8]])
tensor_3 = torch.from_numpy(ndarray)
print("Multiplication: \n", torch.matmul(tensor_2, tensor_3))

# You can also use the @ operator to perform matrix multiplication:
print("Same thing... \n", tensor_2 @ tensor_3)



First row:  tensor([0, 1, 2])
First column:  tensor([0, 3])
Transpose: 
 tensor([[0, 3],
        [1, 4],
        [2, 5]])
Multiplication: 
 tensor([[15, 17, 19],
        [48, 53, 58]])
Same thing... 
 tensor([[15, 17, 19],
        [48, 53, 58]])


### Activity: 
- Complete `matrix_multiplication` function below
- Input: two numpy arrays
- Return: the matrix multiplication as a tensor IF the two numpy arrays can be multiplied
    - returns null if they can't be multiplied

> Recall: For matrix mulitplication of A and B, the number of cols in A must equal the number of rows in B

In [19]:
def matrix_multiplication(A: np.ndarray, B: np.ndarray) -> torch.Tensor:
    return torch.tensor(np.dot(A, B)) if A.shape[1] == B.shape[0] else None

In [20]:
# Test Cases
# Test Case 1: Standard multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
expected_output = torch.tensor([[19, 22], [43, 50]])
output = matrix_multiplication(A, B)
assert torch.equal(output, expected_output), f"Test Case 1 Failed: {output}"

# Test Case 2: Different dimensions but valid for multiplication
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
expected_output = torch.tensor([[58, 64], [139, 154]])
output = matrix_multiplication(A, B)
assert torch.equal(output, expected_output), f"Test Case 2 Failed: {output}"

# Test Case 3: Incompatible dimensions
A = np.array([[1, 2]])
B = np.array([[3, 4], [5, 6], [7, 8]])
output = matrix_multiplication(A, B)
assert output is None, f"Test Case 3 Failed: {output}"

print("All test cases passed!")


All test cases passed!


# Part 2: Automatic Differentiation in PyTorch
- this module in pytorch will allow the automatifc calculation of gradients
- What are gradients?
    - gradients represent the rate of change of functions with respect to params
    - helps identify the difference between predicted outputs and actual labels
- pytorch will automatically create the function needed for backward propagation in ML

In [21]:
# Example 1:

# Define tensors with requires_grad=True to track computation history
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
 
# Perform a computation
z = x**2 + y**3
print("Output tensor z:", z)
 
# Compute gradients - run backpropagation
z.backward()

# Print the gradients
print("Gradient of x:", x.grad)
print("Gradient of y:", y.grad)


Output tensor z: tensor(31., grad_fn=<AddBackward0>)
Gradient of x: tensor(4.)
Gradient of y: tensor(27.)
