# What is PyTorch?
Two main use cases:
1. Leverage numpy arrays on the GPU
2. Deep learning research platform

In [28]:
# Import Libraries
import torch
import numpy as np
import torch.nn as nn

# Part 1: Intro to Tensors
- Tensors are a fundamental data structure similiar to arrays and matrices
- Efficient for math operations on large data 
- The data structure used in pytorch models
- Similiar to a numpy array

In [16]:
# Creating a Tensor from a Numpy Array
ndarray = np.array([1, 2, 3])
t = torch.from_numpy(ndarray)
print("Tensor: ", t)

Tensor:  tensor([1, 2, 3])


### Three Attributes of a Tensor:
1. shape: size of the tensor
2. data type: type of data stored in the tensor
3. device: the device the tensor is stored in (e.g. cpu, gpu)

In [ ]:
print(t.shape)
print(t.dtype)
print(t.device)

### Tensor Operations

In [23]:
ndarray = np.array([[0, 1, 2], [3, 4, 5]])
tensor_2 = torch.from_numpy(ndarray)

# Index first row:
print("First row: ", tensor_2[0])

# Index first column:
print("First column: ", tensor_2[:, 0])

# Transpose the tensor
print("Transpose: \n", tensor_2.T)

# Multiply the Tensor: (Matrix Multiplication)
ndarray = np.array([[2, 2, 2], [3, 3, 3], [6, 7, 8]])
tensor_3 = torch.from_numpy(ndarray)
print("Multiplication: \n", torch.matmul(tensor_2, tensor_3))

# You can also use the @ operator to perform matrix multiplication:
print("Same thing... \n", tensor_2 @ tensor_3)



First row:  tensor([0, 1, 2])
First column:  tensor([0, 3])
Transpose: 
 tensor([[0, 3],
        [1, 4],
        [2, 5]])
Multiplication: 
 tensor([[15, 17, 19],
        [48, 53, 58]])
Same thing... 
 tensor([[15, 17, 19],
        [48, 53, 58]])


### Activity 1: 
- Complete `matrix_multiplication` function below
- Input: two numpy arrays
- Return: the matrix multiplication as a tensor IF the two numpy arrays can be multiplied
    - returns null if they can't be multiplied

> Recall: For matrix mulitplication of A and B, the number of cols in A must equal the number of rows in B

In [12]:
def matrix_multiplication(A: np.ndarray, B: np.ndarray) -> torch.Tensor:
    # Write Code here

In [13]:
# Test Cases
# Test Case 1: Standard multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
expected_output = torch.tensor([[19, 22], [43, 50]])
output = matrix_multiplication(A, B)
assert torch.equal(output, expected_output), f"Test Case 1 Failed: {output}"

# Test Case 2: Different dimensions but valid for multiplication
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
expected_output = torch.tensor([[58, 64], [139, 154]])
output = matrix_multiplication(A, B)
assert torch.equal(output, expected_output), f"Test Case 2 Failed: {output}"

# Test Case 3: Incompatible dimensions
A = np.array([[1, 2]])
B = np.array([[3, 4], [5, 6], [7, 8]])
output = matrix_multiplication(A, B)
assert output is None, f"Test Case 3 Failed: {output}"

print("All test cases passed!")


All test cases passed!


# Part 2: Automatic Differentiation in PyTorch
- this module in pytorch will allow the automatifc calculation of gradients
- What are gradients?
    - gradients represent the rate of change of functions with respect to params
    - helps identify the difference between predicted outputs and actual labels
- pytorch will automatically create the function needed for backward propagation in ML

In [26]:
# Example 1:

# Define tensors with requires_grad=True to track computation history
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
 
# Perform a computation
z = x**2 + y**3
print("Output tensor z:", z)
 
# Compute gradients - run backpropagation
z.backward()

# Print the gradients
print("Gradient of x:", x.grad)
print("Gradient of y:", y.grad)


Output tensor z: tensor(31., grad_fn=<AddBackward0>)
Gradient of x: tensor(4.)
Gradient of y: tensor(27.)


In [29]:
# Example 2 (Optional):
# This example demonstrates how gradients can be put to use:

# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

# 1-step gradient descent.
optimizer.step()

# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())


w:  Parameter containing:
tensor([[ 0.5573, -0.4756,  0.1310],
        [-0.1495, -0.5322,  0.2433]], requires_grad=True)
b:  Parameter containing:
tensor([-0.3484, -0.1480], requires_grad=True)
loss:  2.1264235973358154
dL/dw:  tensor([[ 1.3172, -0.4402,  0.4978],
        [ 0.2199, -0.7606,  0.8396]])
dL/db:  tensor([-0.4920, -0.3344])
loss after 1 step optimization:  2.088127613067627
